# Generated by Django 6.0.3 on 2026-04-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
